// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EnvyNetMessage.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace EnvyFileServer.Net.EnvyNetMessage {

  /// <summary>Holder for reflection information generated from EnvyNetMessage.proto</summary>
  public static partial class EnvyNetMessageReflection {

    #region Descriptor
    /// <summary>File descriptor for EnvyNetMessage.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static EnvyNetMessageReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChRFbnZ5TmV0TWVzc2FnZS5wcm90bxISZW52eWZpbGVzZXJ2ZXIubmV0IuMB",
            "Cg5FbnZ5TmV0TWVzc2FnZRIMCgRkYXRhGAEgASgMEhAKCGRhdGFTaXplGAIg",
            "ASgFEj8KBHR5cGUYAyABKA4yMS5lbnZ5ZmlsZXNlcnZlci5uZXQuRW52eU5l",
            "dE1lc3NhZ2UuTmV0TWVzc2FnZVR5cGUicAoOTmV0TWVzc2FnZVR5cGUSFwoT",
            "TkVUX09QRU5fQ09OTkVDVElPThAAEhgKFE5FVF9DTE9TRV9DT05ORUNUSU9O",
            "EAESFAoQTkVUX0FVVEhfTUVTU0FHRRACEhUKEU5FVF9BVVRIX1JFU1BPTlNF",
            "EANCUgoWc3JjLmVudnlmaWxlc2VydmVyLm5ldEIURW52eU5ldE1lc3NhZ2VQ",
            "cm90b3OqAiFFbnZ5RmlsZVNlcnZlci5OZXQuRW52eU5ldE1lc3NhZ2ViBnBy",
            "b3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::EnvyFileServer.Net.EnvyNetMessage.EnvyNetMessage), global::EnvyFileServer.Net.EnvyNetMessage.EnvyNetMessage.Parser, new[]{ "Data", "DataSize", "Type" }, null, new[]{ typeof(global::EnvyFileServer.Net.EnvyNetMessage.EnvyNetMessage.Types.NetMessageType) }, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class EnvyNetMessage : pb::IMessage<EnvyNetMessage> {
    private static readonly pb::MessageParser<EnvyNetMessage> _parser = new pb::MessageParser<EnvyNetMessage>(() => new EnvyNetMessage());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<EnvyNetMessage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::EnvyFileServer.Net.EnvyNetMessage.EnvyNetMessageReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EnvyNetMessage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EnvyNetMessage(EnvyNetMessage other) : this() {
      data_ = other.data_;
      dataSize_ = other.dataSize_;
      type_ = other.type_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EnvyNetMessage Clone() {
      return new EnvyNetMessage(this);
    }

    /// <summary>Field number for the "data" field.</summary>
    public const int DataFieldNumber = 1;
    private pb::ByteString data_ = pb::ByteString.Empty;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pb::ByteString Data {
      get { return data_; }
      set {
        data_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "dataSize" field.</summary>
    public const int DataSizeFieldNumber = 2;
    private int dataSize_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int DataSize {
      get { return dataSize_; }
      set {
        dataSize_ = value;
      }
    }

    /// <summary>Field number for the "type" field.</summary>
    public const int TypeFieldNumber = 3;
    private global::EnvyFileServer.Net.EnvyNetMessage.EnvyNetMessage.Types.NetMessageType type_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::EnvyFileServer.Net.EnvyNetMessage.EnvyNetMessage.Types.NetMessageType Type {
      get { return type_; }
      set {
        type_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as EnvyNetMessage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(EnvyNetMessage other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Data != other.Data) return false;
      if (DataSize != other.DataSize) return false;
      if (Type != other.Type) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Data.Length != 0) hash ^= Data.GetHashCode();
      if (DataSize != 0) hash ^= DataSize.GetHashCode();
      if (Type != 0) hash ^= Type.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Data.Length != 0) {
        output.WriteRawTag(10);
        output.WriteBytes(Data);
      }
      if (DataSize != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(DataSize);
      }
      if (Type != 0) {
        output.WriteRawTag(24);
        output.WriteEnum((int) Type);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Data.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(Data);
      }
      if (DataSize != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(DataSize);
      }
      if (Type != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(EnvyNetMessage other) {
      if (other == null) {
        return;
      }
      if (other.Data.Length != 0) {
        Data = other.Data;
      }
      if (other.DataSize != 0) {
        DataSize = other.DataSize;
      }
      if (other.Type != 0) {
        Type = other.Type;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            Data = input.ReadBytes();
            break;
          }
          case 16: {
            DataSize = input.ReadInt32();
            break;
          }
          case 24: {
            type_ = (global::EnvyFileServer.Net.EnvyNetMessage.EnvyNetMessage.Types.NetMessageType) input.ReadEnum();
            break;
          }
        }
      }
    }

    #region Nested types
    /// <summary>Container for nested types declared in the EnvyNetMessage message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static partial class Types {
      public enum NetMessageType {
        [pbr::OriginalName("NET_OPEN_CONNECTION")] NetOpenConnection = 0,
        [pbr::OriginalName("NET_CLOSE_CONNECTION")] NetCloseConnection = 1,
        [pbr::OriginalName("NET_AUTH_MESSAGE")] NetAuthMessage = 2,
        [pbr::OriginalName("NET_AUTH_RESPONSE")] NetAuthResponse = 3,
      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
