// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EnvyNetMessage.proto

package src.envyfileserver.net;

public final class EnvyNetMessageProtos {
  private EnvyNetMessageProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface EnvyNetMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:envyfileserver.net.EnvyNetMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bytes data = 1;</code>
     */
    com.google.protobuf.ByteString getData();

    /**
     * <code>int32 dataSize = 2;</code>
     */
    int getDataSize();

    /**
     * <code>.envyfileserver.net.EnvyNetMessage.NetMessageType type = 3;</code>
     */
    int getTypeValue();
    /**
     * <code>.envyfileserver.net.EnvyNetMessage.NetMessageType type = 3;</code>
     */
    src.envyfileserver.net.EnvyNetMessageProtos.EnvyNetMessage.NetMessageType getType();
  }
  /**
   * Protobuf type {@code envyfileserver.net.EnvyNetMessage}
   */
  public  static final class EnvyNetMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:envyfileserver.net.EnvyNetMessage)
      EnvyNetMessageOrBuilder {
    // Use EnvyNetMessage.newBuilder() to construct.
    private EnvyNetMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private EnvyNetMessage() {
      data_ = com.google.protobuf.ByteString.EMPTY;
      dataSize_ = 0;
      type_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private EnvyNetMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {

              data_ = input.readBytes();
              break;
            }
            case 16: {

              dataSize_ = input.readInt32();
              break;
            }
            case 24: {
              int rawValue = input.readEnum();

              type_ = rawValue;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return src.envyfileserver.net.EnvyNetMessageProtos.internal_static_envyfileserver_net_EnvyNetMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return src.envyfileserver.net.EnvyNetMessageProtos.internal_static_envyfileserver_net_EnvyNetMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              src.envyfileserver.net.EnvyNetMessageProtos.EnvyNetMessage.class, src.envyfileserver.net.EnvyNetMessageProtos.EnvyNetMessage.Builder.class);
    }

    /**
     * Protobuf enum {@code envyfileserver.net.EnvyNetMessage.NetMessageType}
     */
    public enum NetMessageType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>NET_OPEN_CONNECTION = 0;</code>
       */
      NET_OPEN_CONNECTION(0),
      /**
       * <code>NET_CLOSE_CONNECTION = 1;</code>
       */
      NET_CLOSE_CONNECTION(1),
      /**
       * <code>NET_AUTH_MESSAGE = 2;</code>
       */
      NET_AUTH_MESSAGE(2),
      /**
       * <code>NET_AUTH_RESPONSE = 3;</code>
       */
      NET_AUTH_RESPONSE(3),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>NET_OPEN_CONNECTION = 0;</code>
       */
      public static final int NET_OPEN_CONNECTION_VALUE = 0;
      /**
       * <code>NET_CLOSE_CONNECTION = 1;</code>
       */
      public static final int NET_CLOSE_CONNECTION_VALUE = 1;
      /**
       * <code>NET_AUTH_MESSAGE = 2;</code>
       */
      public static final int NET_AUTH_MESSAGE_VALUE = 2;
      /**
       * <code>NET_AUTH_RESPONSE = 3;</code>
       */
      public static final int NET_AUTH_RESPONSE_VALUE = 3;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static NetMessageType valueOf(int value) {
        return forNumber(value);
      }

      public static NetMessageType forNumber(int value) {
        switch (value) {
          case 0: return NET_OPEN_CONNECTION;
          case 1: return NET_CLOSE_CONNECTION;
          case 2: return NET_AUTH_MESSAGE;
          case 3: return NET_AUTH_RESPONSE;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<NetMessageType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          NetMessageType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<NetMessageType>() {
              public NetMessageType findValueByNumber(int number) {
                return NetMessageType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return src.envyfileserver.net.EnvyNetMessageProtos.EnvyNetMessage.getDescriptor().getEnumTypes().get(0);
      }

      private static final NetMessageType[] VALUES = values();

      public static NetMessageType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private NetMessageType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:envyfileserver.net.EnvyNetMessage.NetMessageType)
    }

    public static final int DATA_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString data_;
    /**
     * <code>bytes data = 1;</code>
     */
    public com.google.protobuf.ByteString getData() {
      return data_;
    }

    public static final int DATASIZE_FIELD_NUMBER = 2;
    private int dataSize_;
    /**
     * <code>int32 dataSize = 2;</code>
     */
    public int getDataSize() {
      return dataSize_;
    }

    public static final int TYPE_FIELD_NUMBER = 3;
    private int type_;
    /**
     * <code>.envyfileserver.net.EnvyNetMessage.NetMessageType type = 3;</code>
     */
    public int getTypeValue() {
      return type_;
    }
    /**
     * <code>.envyfileserver.net.EnvyNetMessage.NetMessageType type = 3;</code>
     */
    public src.envyfileserver.net.EnvyNetMessageProtos.EnvyNetMessage.NetMessageType getType() {
      src.envyfileserver.net.EnvyNetMessageProtos.EnvyNetMessage.NetMessageType result = src.envyfileserver.net.EnvyNetMessageProtos.EnvyNetMessage.NetMessageType.valueOf(type_);
      return result == null ? src.envyfileserver.net.EnvyNetMessageProtos.EnvyNetMessage.NetMessageType.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!data_.isEmpty()) {
        output.writeBytes(1, data_);
      }
      if (dataSize_ != 0) {
        output.writeInt32(2, dataSize_);
      }
      if (type_ != src.envyfileserver.net.EnvyNetMessageProtos.EnvyNetMessage.NetMessageType.NET_OPEN_CONNECTION.getNumber()) {
        output.writeEnum(3, type_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!data_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, data_);
      }
      if (dataSize_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, dataSize_);
      }
      if (type_ != src.envyfileserver.net.EnvyNetMessageProtos.EnvyNetMessage.NetMessageType.NET_OPEN_CONNECTION.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, type_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof src.envyfileserver.net.EnvyNetMessageProtos.EnvyNetMessage)) {
        return super.equals(obj);
      }
      src.envyfileserver.net.EnvyNetMessageProtos.EnvyNetMessage other = (src.envyfileserver.net.EnvyNetMessageProtos.EnvyNetMessage) obj;

      boolean result = true;
      result = result && getData()
          .equals(other.getData());
      result = result && (getDataSize()
          == other.getDataSize());
      result = result && type_ == other.type_;
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + DATA_FIELD_NUMBER;
      hash = (53 * hash) + getData().hashCode();
      hash = (37 * hash) + DATASIZE_FIELD_NUMBER;
      hash = (53 * hash) + getDataSize();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + type_;
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static src.envyfileserver.net.EnvyNetMessageProtos.EnvyNetMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static src.envyfileserver.net.EnvyNetMessageProtos.EnvyNetMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static src.envyfileserver.net.EnvyNetMessageProtos.EnvyNetMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static src.envyfileserver.net.EnvyNetMessageProtos.EnvyNetMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static src.envyfileserver.net.EnvyNetMessageProtos.EnvyNetMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static src.envyfileserver.net.EnvyNetMessageProtos.EnvyNetMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static src.envyfileserver.net.EnvyNetMessageProtos.EnvyNetMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static src.envyfileserver.net.EnvyNetMessageProtos.EnvyNetMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static src.envyfileserver.net.EnvyNetMessageProtos.EnvyNetMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static src.envyfileserver.net.EnvyNetMessageProtos.EnvyNetMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(src.envyfileserver.net.EnvyNetMessageProtos.EnvyNetMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code envyfileserver.net.EnvyNetMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:envyfileserver.net.EnvyNetMessage)
        src.envyfileserver.net.EnvyNetMessageProtos.EnvyNetMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return src.envyfileserver.net.EnvyNetMessageProtos.internal_static_envyfileserver_net_EnvyNetMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return src.envyfileserver.net.EnvyNetMessageProtos.internal_static_envyfileserver_net_EnvyNetMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                src.envyfileserver.net.EnvyNetMessageProtos.EnvyNetMessage.class, src.envyfileserver.net.EnvyNetMessageProtos.EnvyNetMessage.Builder.class);
      }

      // Construct using src.envyfileserver.net.EnvyNetMessageProtos.EnvyNetMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        data_ = com.google.protobuf.ByteString.EMPTY;

        dataSize_ = 0;

        type_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return src.envyfileserver.net.EnvyNetMessageProtos.internal_static_envyfileserver_net_EnvyNetMessage_descriptor;
      }

      public src.envyfileserver.net.EnvyNetMessageProtos.EnvyNetMessage getDefaultInstanceForType() {
        return src.envyfileserver.net.EnvyNetMessageProtos.EnvyNetMessage.getDefaultInstance();
      }

      public src.envyfileserver.net.EnvyNetMessageProtos.EnvyNetMessage build() {
        src.envyfileserver.net.EnvyNetMessageProtos.EnvyNetMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public src.envyfileserver.net.EnvyNetMessageProtos.EnvyNetMessage buildPartial() {
        src.envyfileserver.net.EnvyNetMessageProtos.EnvyNetMessage result = new src.envyfileserver.net.EnvyNetMessageProtos.EnvyNetMessage(this);
        result.data_ = data_;
        result.dataSize_ = dataSize_;
        result.type_ = type_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof src.envyfileserver.net.EnvyNetMessageProtos.EnvyNetMessage) {
          return mergeFrom((src.envyfileserver.net.EnvyNetMessageProtos.EnvyNetMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(src.envyfileserver.net.EnvyNetMessageProtos.EnvyNetMessage other) {
        if (other == src.envyfileserver.net.EnvyNetMessageProtos.EnvyNetMessage.getDefaultInstance()) return this;
        if (other.getData() != com.google.protobuf.ByteString.EMPTY) {
          setData(other.getData());
        }
        if (other.getDataSize() != 0) {
          setDataSize(other.getDataSize());
        }
        if (other.type_ != 0) {
          setTypeValue(other.getTypeValue());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        src.envyfileserver.net.EnvyNetMessageProtos.EnvyNetMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (src.envyfileserver.net.EnvyNetMessageProtos.EnvyNetMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes data = 1;</code>
       */
      public com.google.protobuf.ByteString getData() {
        return data_;
      }
      /**
       * <code>bytes data = 1;</code>
       */
      public Builder setData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes data = 1;</code>
       */
      public Builder clearData() {
        
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }

      private int dataSize_ ;
      /**
       * <code>int32 dataSize = 2;</code>
       */
      public int getDataSize() {
        return dataSize_;
      }
      /**
       * <code>int32 dataSize = 2;</code>
       */
      public Builder setDataSize(int value) {
        
        dataSize_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 dataSize = 2;</code>
       */
      public Builder clearDataSize() {
        
        dataSize_ = 0;
        onChanged();
        return this;
      }

      private int type_ = 0;
      /**
       * <code>.envyfileserver.net.EnvyNetMessage.NetMessageType type = 3;</code>
       */
      public int getTypeValue() {
        return type_;
      }
      /**
       * <code>.envyfileserver.net.EnvyNetMessage.NetMessageType type = 3;</code>
       */
      public Builder setTypeValue(int value) {
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.envyfileserver.net.EnvyNetMessage.NetMessageType type = 3;</code>
       */
      public src.envyfileserver.net.EnvyNetMessageProtos.EnvyNetMessage.NetMessageType getType() {
        src.envyfileserver.net.EnvyNetMessageProtos.EnvyNetMessage.NetMessageType result = src.envyfileserver.net.EnvyNetMessageProtos.EnvyNetMessage.NetMessageType.valueOf(type_);
        return result == null ? src.envyfileserver.net.EnvyNetMessageProtos.EnvyNetMessage.NetMessageType.UNRECOGNIZED : result;
      }
      /**
       * <code>.envyfileserver.net.EnvyNetMessage.NetMessageType type = 3;</code>
       */
      public Builder setType(src.envyfileserver.net.EnvyNetMessageProtos.EnvyNetMessage.NetMessageType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.envyfileserver.net.EnvyNetMessage.NetMessageType type = 3;</code>
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:envyfileserver.net.EnvyNetMessage)
    }

    // @@protoc_insertion_point(class_scope:envyfileserver.net.EnvyNetMessage)
    private static final src.envyfileserver.net.EnvyNetMessageProtos.EnvyNetMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new src.envyfileserver.net.EnvyNetMessageProtos.EnvyNetMessage();
    }

    public static src.envyfileserver.net.EnvyNetMessageProtos.EnvyNetMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<EnvyNetMessage>
        PARSER = new com.google.protobuf.AbstractParser<EnvyNetMessage>() {
      public EnvyNetMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new EnvyNetMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<EnvyNetMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<EnvyNetMessage> getParserForType() {
      return PARSER;
    }

    public src.envyfileserver.net.EnvyNetMessageProtos.EnvyNetMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_envyfileserver_net_EnvyNetMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_envyfileserver_net_EnvyNetMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024EnvyNetMessage.proto\022\022envyfileserver.n" +
      "et\"\343\001\n\016EnvyNetMessage\022\014\n\004data\030\001 \001(\014\022\020\n\010d" +
      "ataSize\030\002 \001(\005\022?\n\004type\030\003 \001(\01621.envyfilese" +
      "rver.net.EnvyNetMessage.NetMessageType\"p" +
      "\n\016NetMessageType\022\027\n\023NET_OPEN_CONNECTION\020" +
      "\000\022\030\n\024NET_CLOSE_CONNECTION\020\001\022\024\n\020NET_AUTH_" +
      "MESSAGE\020\002\022\025\n\021NET_AUTH_RESPONSE\020\003BR\n\026src." +
      "envyfileserver.netB\024EnvyNetMessageProtos" +
      "\252\002!EnvyFileServer.Net.EnvyNetMessageb\006pr" +
      "oto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_envyfileserver_net_EnvyNetMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_envyfileserver_net_EnvyNetMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_envyfileserver_net_EnvyNetMessage_descriptor,
        new java.lang.String[] { "Data", "DataSize", "Type", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
