#pragma once

#define NOMINMAX
#include <Windows.h>

#include "Enums.hpp"
#include "vmatrix.h"
#include "qangle.hpp"
#include "quaternion.hpp"
#include "vector.hpp"
#include "studio.hpp"

#include "IAppSystem.hpp"
#include "ClientDll.hpp"
#include "IClientEntity.hpp"
#include "IClientEntityList.hpp"
#include "IClientMode.hpp"
#include "IConVar.hpp"
#include "ICvar.hpp"
#include "IEngineTrace.hpp"
#include "IVEngineClient.hpp"
#include "IVDebugOverlay.hpp"
#include "ISurface.hpp"
#include "CInput.hpp"
#include "IVModelInfoClient.hpp"
#include "IVModelRender.hpp"
#include "IRenderView.hpp"
#include "IGameEventmanager.hpp"
#include "IMaterialSystem.hpp"
#include "IMoveHelper.hpp"
#include "IMDLCache.hpp"
#include "IPrediction.hpp"
#include "IPanel.hpp"
#include "IEngineSound.hpp"
#include "IViewRender.hpp"
#include "CClientState.hpp"
#include "cgamerules.hpp"
#include "IPhysics.hpp"
#include "globalvars.hpp"
#include "inetchannelinfo.hpp"
#include "animstate.hpp"

#include "Convar.h"
#include "CUserCmd.hpp"
#include "glowoutlineeffect.hpp"
#include "keyvalues.hpp"

#include "netvars.h"
